CREATE TABLE ROBOS_BOGOTA(
	DOCUMENTO NUMBER,
	FECHA date NULL,
	DEPARTAMENTO varchar(20) NULL,
	MUNICIPIO varchar(20) NULL,
	DIA varchar(10) NULL,
	HORA TIMESTAMP NULL,
	SITIO varchar(50) NULL,
	AGRESOR varchar(25) NULL,
	VICTIMA varchar(25) NULL,
	EDAD int NULL,
	PAIS_NACIMIENTO varchar(10) NULL,
	CLASE_EMPLEADO varchar(20) NULL,
	PROFESION varchar(75) NULL,
	ESCOLARIDAD varchar(15) NULL,
	CODIGO_DANE varchar(10) NULL
);